from gym_custom.envs.pendulum import QPendulumEnv
from gym_custom.envs.springmass import SpringMassEnv
from gym_custom.envs.springmass_pos import SpringMassPosEnv
from gym_custom.envs.cartpole import CartPoleEnv
from gym_custom.envs.cartpole import CartPolePosEnv
from gym_custom.envs.im_pendulum import ImPendulumEnv
from gym_custom.envs.coupled_masspring import CoupledMassSpringEnv
from gym_custom.envs.pendulum_mod import PendulumModEnv
from gym_custom.envs.pendulum_mod import PendulumModPosEnv
